### ISSUE TITLE
source_FILE.py

### ISSUE THREAD

**Issue by edmondchuc** [CSIRO-enviro-informatics/VocPrez#10]
On system startup, read in all RDF files and serialise them to disk as pickle files. Add the list to the in-memory `VOCABS` object. Ensure that web requests are then read from the pickle files or the `VOCABS` object as needed.

**Comment by nicholascar** [comment]
Read all RDF file (indicated by ending in .ttl, .rdf, .owl or .json) in data/ by default or other location specified in config.

From read RDF files, complete `VOCABS` entries for them, so only the following:

    'KEY': {
        'source': VocabSource.FILE,
        'title': 'TITLE'
}

So you only need TITLE (dct:title of the vocab/ConceptScheme object) and to make up any KEY.

**Comment by nicholascar** [comment]
`FILE.list_vocabularies` is the list of vocabularies, as called by config/__init__.py, so you'll get one results per vocab file from it added into `VOCABS` in config/__init__.py . list_concepts is the list of concepts!
