### ISSUE TITLE
Implement concept_hierarchy across all sources

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#15]
Example working code is in source_VOCBENCH

**Comment by edmondchuc** [comment]
Working on all sources.

Weird issue, some RVA sources are causing a HTTP error within rdflib.

**Comment by edmondchuc** [comment]
Fixed the weird issue. It's because source files retrieved from RVA sometimes fail. There must be some issue on their end. I've added some try and excepts as it seems like it works after a few attempts.

**Comment by edmondchuc** [comment]
All concept hierarchies are now queried using SPARQL. This resulted in this issue: https://github.com/CSIRO-enviro-informatics/VocPrez/issues/17

The concept hierarchy property in the Vocabulary class is now parsed to HTML before feeding into the template.
