### ISSUE TITLE
Display vocabs register with mutiple properties

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#21]
Currently the vocabs list just shows title as a hyperlink to the vocab item entry. We need, at least, the vocab title, creator/owner, perhaps version.

**Comment by edmondchuc** [comment]
Currently supported metadata for the registers:

**Vocabulary Register:**
* dct:creator
* dct:created
* dct:modified 
* owl:versionInfo

**Concept Register:**
* dct:created 
* dct:modified

**Comment by nicholascar** [comment]
Covered by further templated work in last few months
