### ISSUE TITLE
Concept template must handle certain properties

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#22]
Currently the Concept template is only showing data properties of a Concept (descruiption, altLabels etc.) and no semantic properties (exactMatch, broadMatch etc.). 

See http://vocabs.gsq.cat/object?vocab_id=GSQ_Simple_Lithology&uri=http://linkend.data.gov.au/def/gsq-simple-lithology%23Igneous_Rock. This should show skos:exactMatch <http://resource.geosciml.org/classifier/cgi/lithology/igneous_rock>

**Comment by edmondchuc** [comment]
https://github.com/CSIRO-enviro-informatics/VocPrez/commit/75eaa4cdb67acf0809bad097789a3d3e6823e67f
https://github.com/CSIRO-enviro-informatics/VocPrez/commit/dabe691aaf1a4fffea52bc2d7dcb2a8d55c06bd3
https://github.com/CSIRO-enviro-informatics/VocPrez/commit/0630669ffca3a2e7e3bc3b35dc60f3a7b9337b96
https://github.com/CSIRO-enviro-informatics/VocPrez/commit/4de30fbc8d86a541422f86ca945630cb0b1ee5d6
