### ISSUE TITLE
Reduce space occupied by "Automated Pagination" text

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#25]
Perhaps create a CSS/JavaScript div that is titled "Austomated Pagination" but only displays as a small box and then displayed the full info, as per current VocPrez/LDAPI, when clicked on.

**Comment by edmondchuc** [comment]
I was thinking about this today too Nick. What do you think if we make it an information button titled "Automated Pagination" and when clicked on, it brings up a modal?

**Comment by nicholascar** [comment]
Yes, that's what I was thinking of.

There's a reduced set of wording for the Automated Pagination being used here: http://www.linked.data.gov.au/cat/def/ so perhaps that grey box can just become a modal although it actually doesn't look too bad the way I've done it there as it is!

Maybe initially style VocPrez similar to http://www.linked.data.gov.au/cat/def/ and then let's see if that covers it. If not, go modal.

**Comment by edmondchuc** [comment]
* Updated display of *Automated Pagination* info to a collapsible view. 
* Removed old HTML table layout and converted it to using [Bootstrap 4 Grid](https://github.com/m-spyratos/bootstrap-4-grid) (size: 52KB). Note: this is only Bootstrap 4 Grid and not the whole framework so the size is extremely small. 
  * This also means that the website is now fully **responsive**.
