### ISSUE TITLE
List all 50+ CGI vocabs

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#3]
Using the source.RVA, list all the vocabs published by CGI for GeoSciML (see [GeoSciML Vocabularies](http://resource.geosciml.org/def/voc/))

**Comment by edmondchuc** [comment]
Added vocabularies.

Commit: https://github.com/CSIRO-enviro-informatics/VocPrez/commit/a58c7ace3f0e724692e6bdecbceaf74221445052
