### ISSUE TITLE
Create a Concept list view for CKAN

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#4]
Add a view to VocPrez' [SkosRegisterRenderer](https://github.com/CSIRO-enviro-informatics/VocPrez/blob/master/model/skos_register.py) to supply a JSON list that you can use in CKAN schema.

**Comment by edmondchuc** [comment]
Added a view for the `SkosRegisterRenderer` which renders a list of register items in the `application/sparql-results+json` format.

Commit : https://github.com/CSIRO-enviro-informatics/VocPrez/commit/f67d232f183ffd89a02cff11c0b79f327bc43329
