### ISSUE TITLE
Check GSQ theming with GSQ

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#7]
The gsq branch of VocPrez has GSQ styling. Check that this is appropriate with the GSQ Project Manager, Drew Cox. Ask him who needs to review it for it to be allowed to be released.

**Comment by edmondchuc** [comment]
I have sent an email to the project manager of the GSQ project. Awaiting reply.

**Comment by edmondchuc** [comment]
Project manager has commented that the current theme looks fine. They have mentioned that they would like to review it again later in development to standardise the appearance with the overall project.
