### ISSUE TITLE
Implement Alternates View for Vocab, Concept

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#8]
While Alternate View is working for VocPrez things (e.g. Vocab http://13.236.122.60/vocprez/vocabulary/rva-52?_view=alternates & Concept http://13.236.122.60/vocprez/object?vocab_id=rva-52&uri=http://resource.geosciml.org/classifier/cgi/contacttype/contact) the various Views & Formats don't work but they need to.

You may have to implement additional outputs in the ConceptRendered & SkosRegisterRenderer classes to support RDF delivery.

**Comment by edmondchuc** [comment]
Completed.
