### ISSUE TITLE
Improving HTML template issues

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/VocPrez#9]
- [x] See the (lack of) spacing between items in http://13.236.122.60/vocprez/object?vocab_id=rva-52&uri=http://resource.geosciml.org/classifier/cgi/contacttype/contact like the label 'Narrower' and the list of concepts. 

- [x] Please just improve the padding.

- [x] Also, can the Concept URI, like http://resource.geosciml.org/classifier/cgi/contacttype/contact in the example above, be made as a hyperlink like 'Contact Type' is in the link above.

- [x] The About page, http://13.236.122.60/vocprez/about, is missing its diagram.  Check the controller function handling the /about endpoint to ensure it is processing the Markdown data correctly and adding in a correct link to the image (it is http://13.236.122.60/static/system.svg but should be http://13.236.122.60/vocprez/static/system.svg so needs to pick up the 'vocprez' bit from config).

**Comment by edmondchuc** [comment]
Fixed missing diagram image: https://github.com/CSIRO-enviro-informatics/VocPrez/commit/ba5d423685c38eb2a2e8ea8ac7eace2f312b1cc2

**Comment by edmondchuc** [comment]
Added extra padding to fix the spacing issue: https://github.com/CSIRO-enviro-informatics/VocPrez/commit/d0a0e3b2a2e38e7f632bbdcab70eef5609f2accc

**Comment by edmondchuc** [comment]
Made Concept URI a hyperlink: https://github.com/CSIRO-enviro-informatics/VocPrez/commit/cd988c7a66834493c7d20e7ff3e279e03e0e20e8
